local stage_ui=require("stageUI.stage_ui")
local styles=require("stageUI.styles")
function init(self)
	msg.post(".", "acquire_input_focus")
	self.stage=stage_ui.Stage.new(styles)
	self.stage:add(stage_ui.Label:new("label","default"))
	self.stage:add(stage_ui.Button:new("button","default",function() print("callback") end))
	self.stage:add(stage_ui.Text_button:new("text_button","default",function() print("callback") end))
	self.stage:add(stage_ui.Checkbox:new("checkbox","default",function() print("callback") end))
	local radio1=stage_ui.Radio:new("radio1","default",function() print("callback") end)
	local radio2=stage_ui.Radio:new("radio2","default",function() print("callback") end)
	local radio_group=stage_ui.Radio_group:new()
	radio_group:add(radio1)
	radio_group:add(radio2)
	
	self.stage:add(radio1)
	self.stage:add(radio2)
end

function final(self)
    msg.post(".", "release_input_focus")
end

function update(self, dt)
    -- Add update code here
    -- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
    -- Add message-handling code here
    -- Remove this function if not needed
end

function on_input(self, action_id, action)
    self.stage:on_input(action_id,action)
		--print(self.button:hit(action.x,action.y))
end

function on_reload(self)
    -- Add input-handling code here
    -- Remove this function if not needed
end
