local stage_ui=require("stageUI.stage_ui")
local styles=require("stageUI.styles")
function init(self)
	msg.post(".", "acquire_input_focus")
	self.stage=stage_ui.Stage.new(styles)
	local label=stage_ui.Label:new("label","default")
	
	local magic2 = gui.clone_tree(label.root_node)
	local label2=stage_ui.Label:new("label","default",magic2)
	label2:set_text("AWESOME TEST 2")
	label:set_text("test text")
	self.stage:add(label)
	local button=stage_ui.Button:new("button","default",function() print("callback") end)
	self.stage:add(button)
	self.stage:add(stage_ui.Button:new("button1","default"))
end

function final(self)
    msg.post(".", "release_input_focus")
end

function update(self, dt)
    -- Add update code here
    -- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
    -- Add message-handling code here
    -- Remove this function if not needed
end

function on_input(self, action_id, action)
    self.stage:on_input(action_id,action)
		--print(self.button:hit(action.x,action.y))
end

function on_reload(self)
    -- Add input-handling code here
    -- Remove this function if not needed
end
